services:
  mastchain-ais:
    image: ghcr.io/c-man-the-man/mastchain-ais:latest
    container_name: mastchain-ais
    restart: unless-stopped

    devices:
      - /dev/bus/usb:/dev/bus/usb

    ports:
      - "8100:8100"  # changeable depending on local needs, the same port number has to be added to the -N flag

    volumes:
      - mastchain_data:/data

    environment:
      TZ: Europe/Madrid  # change to your local timezone

    command: >
      -v 30
      -N 8100
      -H https://api.mastchain.io/api/submit
      USERPWD ADD_YOUR_MASTCHAIN_TOKEN_HERE
      INTERVAL 60
      --logfile /data/aiscatcher.log
      --loglevel info

volumes:
  mastchain_data:
